apiVersion: 1

deleteDatasources:
  - name: SignalAI Prometheus
    orgId: 1

prune: true

datasources:
  - name: SignalAI Prometheus
    uid: signalai-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      timeInterval: 5s
