from __future__ import annotations

import math

from app.tradinggpt.execution import ExecutionPlan

from .models import (
    AccountRiskContext,
    RiskDecision,
    RiskLimits,
)


class RiskManager:
    """
    Applies account-level safety limits to an execution plan.

    The manager never increases the position generated by the
    Execution Planner. It can only allow it, reduce it, or deny it.
    """

    @classmethod
    def evaluate(
        cls,
        *,
        execution_plan: ExecutionPlan,
        account: AccountRiskContext,
        limits: RiskLimits | None = None,
    ) -> RiskDecision:
        limits = limits or RiskLimits()

        cls._validate_account(account)
        cls._validate_limits(limits)

        daily_loss_percent = cls._daily_loss_percent(account)
        drawdown_percent = cls._drawdown_percent(account)
        exposure_percent_before = cls._percent(
            account.current_exposure_value,
            account.equity,
        )

        original_quantity = max(
            float(execution_plan.position_quantity),
            0.0,
        )
        original_value = max(
            float(execution_plan.position_value),
            0.0,
        )
        original_risk = max(
            float(execution_plan.actual_risk_amount),
            0.0,
        )

        denial_reasons: list[str] = []

        if execution_plan.status != "READY":
            denial_reasons.append(
                "Execution plan is not ready for trading."
            )

        if daily_loss_percent >= limits.max_daily_loss_percent:
            denial_reasons.append(
                "Maximum daily loss limit has been reached."
            )

        if drawdown_percent >= limits.max_drawdown_percent:
            denial_reasons.append(
                "Maximum account drawdown limit has been reached."
            )

        if account.open_positions >= limits.max_open_positions:
            denial_reasons.append(
                "Maximum number of open positions has been reached."
            )

        maximum_exposure_value = (
            account.equity
            * limits.max_total_exposure_percent
            / 100.0
        )
        available_exposure_value = max(
            maximum_exposure_value
            - account.current_exposure_value,
            0.0,
        )

        if available_exposure_value <= 0:
            denial_reasons.append(
                "No account exposure capacity remains."
            )

        maximum_correlated_value = (
            account.equity
            * limits.max_correlated_exposure_percent
            / 100.0
        )
        available_correlated_value = max(
            maximum_correlated_value
            - account.correlated_exposure_value,
            0.0,
        )

        if available_correlated_value <= 0:
            denial_reasons.append(
                "Maximum correlated exposure has been reached."
            )

        if original_quantity <= 0 or original_value <= 0:
            denial_reasons.append(
                "Execution plan has no executable position size."
            )

        if denial_reasons:
            return cls._deny(
                execution_plan=execution_plan,
                account=account,
                daily_loss_percent=daily_loss_percent,
                drawdown_percent=drawdown_percent,
                exposure_percent_before=(
                    exposure_percent_before
                ),
                reasons=denial_reasons,
            )

        approved_value = min(
            original_value,
            available_exposure_value,
            available_correlated_value,
        )

        if approved_value < limits.minimum_position_value:
            return cls._deny(
                execution_plan=execution_plan,
                account=account,
                daily_loss_percent=daily_loss_percent,
                drawdown_percent=drawdown_percent,
                exposure_percent_before=(
                    exposure_percent_before
                ),
                reasons=[
                    (
                        "Approved position value is below the "
                        "minimum executable position value."
                    )
                ],
            )

        size_multiplier = min(
            approved_value / original_value,
            1.0,
        )

        approved_quantity = cls._round_down(
            original_quantity * size_multiplier,
            12,
        )
        approved_value = cls._round_money(
            original_value * size_multiplier
        )
        approved_risk = cls._round_money(
            original_risk * size_multiplier
        )

        exposure_after_value = (
            account.current_exposure_value
            + approved_value
        )
        correlated_after_value = (
            account.correlated_exposure_value
            + approved_value
        )

        exposure_percent_after = cls._percent(
            exposure_after_value,
            account.equity,
        )
        correlated_exposure_percent_after = cls._percent(
            correlated_after_value,
            account.equity,
        )

        reasons = [
            (
                "Daily loss, drawdown, open-position and "
                "exposure checks passed."
            )
        ]
        warnings: list[str] = []

        if size_multiplier < 1.0:
            status = "REDUCE_SIZE"
            reasons.append(
                "Position size was reduced to comply with risk limits."
            )

            if approved_value == cls._round_money(
                available_exposure_value
            ):
                warnings.append(
                    "Position was constrained by total exposure."
                )

            if approved_value == cls._round_money(
                available_correlated_value
            ):
                warnings.append(
                    "Position was constrained by correlated exposure."
                )
        else:
            status = "ALLOW"
            reasons.append(
                "The full execution-plan position is approved."
            )

        return RiskDecision(
            status=status,
            symbol=execution_plan.symbol,
            original_position_quantity=original_quantity,
            original_position_value=original_value,
            approved_position_quantity=approved_quantity,
            approved_position_value=approved_value,
            approved_risk_amount=approved_risk,
            size_multiplier=round(size_multiplier, 8),
            daily_loss_percent=daily_loss_percent,
            drawdown_percent=drawdown_percent,
            exposure_percent_before=exposure_percent_before,
            exposure_percent_after=exposure_percent_after,
            correlated_exposure_percent_after=(
                correlated_exposure_percent_after
            ),
            reasons=tuple(reasons),
            warnings=tuple(warnings),
        )

    @staticmethod
    def _validate_account(
        account: AccountRiskContext,
    ) -> None:
        if account.equity <= 0:
            raise ValueError("Account equity must be positive.")

        if account.peak_equity <= 0:
            raise ValueError(
                "Peak account equity must be positive."
            )

        if account.open_positions < 0:
            raise ValueError(
                "Open position count cannot be negative."
            )

        if account.current_exposure_value < 0:
            raise ValueError(
                "Current exposure cannot be negative."
            )

        if account.correlated_exposure_value < 0:
            raise ValueError(
                "Correlated exposure cannot be negative."
            )

    @staticmethod
    def _validate_limits(limits: RiskLimits) -> None:
        percentage_fields = {
            "max_daily_loss_percent": (
                limits.max_daily_loss_percent
            ),
            "max_drawdown_percent": (
                limits.max_drawdown_percent
            ),
            "max_total_exposure_percent": (
                limits.max_total_exposure_percent
            ),
            "max_correlated_exposure_percent": (
                limits.max_correlated_exposure_percent
            ),
        }

        for name, value in percentage_fields.items():
            if value <= 0 or value > 100:
                raise ValueError(
                    f"{name} must be between 0 and 100."
                )

        if limits.max_open_positions <= 0:
            raise ValueError(
                "Maximum open positions must be positive."
            )

        if limits.minimum_position_value < 0:
            raise ValueError(
                "Minimum position value cannot be negative."
            )

    @staticmethod
    def _daily_loss_percent(
        account: AccountRiskContext,
    ) -> float:
        daily_loss = max(-account.daily_pnl, 0.0)

        return RiskManager._percent(
            daily_loss,
            account.equity,
        )

    @staticmethod
    def _drawdown_percent(
        account: AccountRiskContext,
    ) -> float:
        drawdown = max(
            account.peak_equity - account.equity,
            0.0,
        )

        return RiskManager._percent(
            drawdown,
            account.peak_equity,
        )

    @staticmethod
    def _percent(
        value: float,
        base: float,
    ) -> float:
        if base <= 0:
            return 0.0

        return round(
            value / base * 100.0,
            6,
        )

    @staticmethod
    def _round_money(value: float) -> float:
        return round(value, 8)

    @staticmethod
    def _round_down(
        value: float,
        decimals: int,
    ) -> float:
        factor = 10 ** decimals

        return math.floor(value * factor) / factor

    @classmethod
    def _deny(
        cls,
        *,
        execution_plan: ExecutionPlan,
        account: AccountRiskContext,
        daily_loss_percent: float,
        drawdown_percent: float,
        exposure_percent_before: float,
        reasons: list[str],
    ) -> RiskDecision:
        correlated_percent = cls._percent(
            account.correlated_exposure_value,
            account.equity,
        )

        return RiskDecision(
            status="DENY",
            symbol=execution_plan.symbol,
            original_position_quantity=max(
                float(execution_plan.position_quantity),
                0.0,
            ),
            original_position_value=max(
                float(execution_plan.position_value),
                0.0,
            ),
            approved_position_quantity=0.0,
            approved_position_value=0.0,
            approved_risk_amount=0.0,
            size_multiplier=0.0,
            daily_loss_percent=daily_loss_percent,
            drawdown_percent=drawdown_percent,
            exposure_percent_before=exposure_percent_before,
            exposure_percent_after=exposure_percent_before,
            correlated_exposure_percent_after=(
                correlated_percent
            ),
            reasons=tuple(reasons),
            warnings=(),
        )
